
artifacts_root : artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    data_url_path: "https://raw.githubusercontent.com/RS4327/RAWDATA/main/insurance_claims.csv"
    data_load_path: artifacts/data_ingestion/data_ingestion.csv
    
data_preprocessing:
    # =================== Directory and Paths ===================
    root_dir: artifacts/data_validation_preprocessing
    validation_data_path: artifacts/Data_Ingestion/data_ingestion.csv
    cleaned_data_path: artifacts/data_validation_preprocessing/cleaned_data.csv
    preprocessing_data_path: artifacts/data_validation_preprocessing/scaler.pkl
    encoded_data_path: artifacts/data_validation_preprocessing/encoded_data.csv
    # ================== Data Splitting Config ===================
    data_test_size: 0.2
    data_random_state: 43
    # ================== Validation Rules =========================
    allowed_missing_percentage: 5 # Threshold for missing values for columns
    allowed_outlier_std: 3 # Number of Standard devaitions for outlier
    # =================== preprocessing Config ===================
    encoding_strategy: "lable"      # lable or onehot
    scaling_strategy: "standard"    #Standard or minmax
    imputation_strategy: "mean"     # mean ,median,and mode
    handling_outlier: True
    handling_missing: True
    save_intermediate: True         # Whether to save clean dataset before split
data_model:
    root_dir: artifacts/data_model
    logistic_model_path: artifacts/data_model/logistic_model.pkl
    randomforest_model_path: artifacts/data_model/randomforest_model.pkl
    scaler_path: artifacts/data_model/scaler.pkl
    Logistic_Regression:
        solver: lbfgs
        max_iter: 500
        class_weight: balanced
        c: 1.0
        random_state: 42
    Random_Forest:
        n_estimators: 200
        max_depth: 10
        class_weight: balanced
        random_state: 42
    Decision_Tree:
        max_depth: 10
        class_weight: balanced
        random_state: 42
    KNeighbors: 
        n_neighbors: 5
    SVM:
        kernal: rbf
        probability: True
        class_weight: balanced
        random_state: 42
    Gradient_Boosting:
        random_state: 42
    AdaBoost:
        random_state: 42
    XGBoost:
        scale_pos_weight : ((len(y_train) - sum(y_train)) / sum(y_train))
        use_label_encoder: False
        eval_metric : logloss
        random_state: 42
    LightGBM:
        class_weight: balanced
        random_state: 42
    CatBoost: 
        verbose: 0
        random_state: 42